name: jolibee_app_clone
description: A Jollibee App Clone

publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:
  assets:
    - assets/
    - assets/home/




  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
